name: Trigger E2E Test Build

on:
  issue_comment:
    types: [created]

jobs:
  notify-e2e-repo:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/ready_to_test')
    runs-on: ubuntu-latest
    steps:
      - name: Set up branch name
        id: set_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Repository Dispatch to E2E Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.E2E_PTA }}
          repository: 'PalladioSimulator/Palladio-Analyzer-Slingshot-Default-Extensions'
          event-type: 'build-trigger'
          client-payload: '{"slingshot_extension_pcm_core_branch": "${{ env.BRANCH_NAME }}"}'
